CREATE TABLE TASK (
 TASKID      int NOT NULL,
 TASKNAME     VARCHAR(50),
 DESCRIPTION  VARCHAR(500),
  PRIORITY   int NOT NULL,
  NOTES      VARCHAR(500),
  OWNERID    int NOT NULL,
  CREATORID  int NOT NULL,
  CREATEDON DATE,
  MODIFIED DATE
 CONSTRAINT TASK_PRIMARY_KEY PRIMARY KEY (TASKID));


CREATE TABLE EMPLOYEE(
EMPLOYEEID INT NOT NULL,
EMPLOYEENAME VARCHAR(30),
TASKID INT NOT NULL
CONSTRAINT EMPLOYEE_FOREIGN_KEY FOREIGN KEY (TASKID) REFERENCES TASK (TASKID),
CONSTRAINT EMPLOYEE_PRIMARY_KEY PRIMARY KEY (EMPLOYEEID));

CREATE TABLE ADMIN(
ADMINID INT NOT NULL,
ADMINNAME VARCHAR(20),
TASKID INT NOT NULL
CONSTRAINT ADMIN_FOREIGN_KEY FOREIGN KEY (TASKID) REFERENCES TASK (TASKID),
CONSTRAINT ADMIN_PRIMARY_KEY PRIMARY KEY (ADMINID));




